# Generated by Django 4.1.3 on 2022-11-09 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adrese',
            fields=[
                ('AdresaID', models.AutoField(primary_key=True, serialize=False)),
                ('Judet', models.CharField(max_length=30)),
                ('Localitate', models.CharField(max_length=30)),
                ('Adresa', models.CharField(max_length=70)),
                ('CodPostal', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Adrese',
            },
        ),
        migrations.CreateModel(
            name='Clienti',
            fields=[
                ('ClientID', models.AutoField(primary_key=True, serialize=False)),
                ('Nume', models.CharField(max_length=45)),
                ('Prenume', models.CharField(max_length=45)),
                ('Email', models.CharField(max_length=50)),
                ('StatusCont', models.CharField(max_length=30)),
                ('DataNastere', models.DateField(blank=True, null=True)),
                ('DataCreareCont', models.DateField()),
                ('Gender', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('AdresaID', models.ForeignKey(blank=True, db_column='AdresaID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cosmetics.adrese')),
            ],
            options={
                'verbose_name_plural': 'Clienti',
            },
        ),
        migrations.CreateModel(
            name='Comenzi',
            fields=[
                ('ComandaID', models.AutoField(primary_key=True, serialize=False)),
                ('Pret', models.IntegerField()),
                ('DataCreare', models.DateField()),
                ('Status', models.CharField(max_length=30)),
                ('AdresaID', models.ForeignKey(blank=True, db_column='AdresaID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cosmetics.adrese')),
                ('ClientID', models.ForeignKey(blank=True, db_column='ClientID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cosmetics.clienti')),
            ],
            options={
                'verbose_name_plural': 'Comenzi',
            },
        ),
        migrations.CreateModel(
            name='Produse',
            fields=[
                ('ProdusID', models.AutoField(primary_key=True, serialize=False)),
                ('Denumire', models.CharField(max_length=50)),
                ('Producator', models.CharField(max_length=45)),
                ('DataAdaugarii', models.DateField()),
                ('Status', models.CharField(max_length=45)),
                ('Pret', models.FloatField(blank=True, null=True)),
                ('Cantitate', models.IntegerField(blank=True, default=0, null=True)),
                ('Descriere', models.TextField(max_length=8000)),
            ],
            options={
                'verbose_name_plural': 'Produse',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('ReviewID', models.AutoField(primary_key=True, serialize=False)),
                ('DataCrearii', models.DateField()),
                ('Titlu', models.CharField(max_length=45)),
                ('Content', models.TextField(max_length=500)),
                ('Nota', models.SmallIntegerField()),
                ('ClientID', models.ForeignKey(blank=True, db_column='ClientID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cosmetics.clienti')),
                ('ProdusID', models.ForeignKey(blank=True, db_column='ProdusID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cosmetics.produse')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='ProduseComandate',
            fields=[
                ('ProdusComandatID', models.AutoField(primary_key=True, serialize=False)),
                ('Cantitate', models.IntegerField()),
                ('ComandaID', models.ForeignKey(blank=True, db_column='ComandaID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cosmetics.comenzi')),
                ('ProdusID', models.ForeignKey(blank=True, db_column='ProdusID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cosmetics.produse')),
            ],
            options={
                'verbose_name_plural': 'ProduseComandate',
            },
        ),
        migrations.CreateModel(
            name='PozeProduse',
            fields=[
                ('PozaProdusID', models.AutoField(primary_key=True, serialize=False)),
                ('Path', models.CharField(max_length=160)),
                ('ProdusID', models.ForeignKey(blank=True, db_column='ProdusID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cosmetics.produse')),
            ],
            options={
                'verbose_name_plural': 'PozeProduse',
            },
        ),
    ]
