# Generated by Django 4.1.3 on 2022-11-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienti',
            name='Password',
            field=models.CharField(default='', max_length=45),
        ),
    ]
