# Generated by Django 4.1.3 on 2022-11-20 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0003_alter_clienti_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduseInCos',
            fields=[
                ('ProdusInCosID', models.AutoField(primary_key=True, serialize=False)),
                ('ClientID', models.ForeignKey(blank=True, db_column='ClientID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cosmetics.clienti')),
                ('ProdusID', models.ForeignKey(blank=True, db_column='ProdusID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cosmetics.produse')),
            ],
            options={
                'verbose_name_plural': 'ProduseInCos',
            },
        ),
    ]
