# Generated by Django 4.1.3 on 2023-01-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0004_produseincos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comenzi',
            name='Pret',
            field=models.FloatField(),
        ),
    ]
